### ISSUE TITLE
Game doesnt work in computers that are not mine own

### ISSUE THREAD

**Issue by Matuiss2** [Matuiss2/Snake-python#1]
The path to the songs and sfxs are not yet relative.

**Comment by McSinyx** [comment]
While your game works for me, you might still want to take a look at Python [pkg_resources.resource_filename](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#resource-extraction) and [Python guide on packaging](https://packaging.python.org/tutorials/distributing-packages/).

If you have any question, feel free to ask. I personally maintaining 2 games on PyPI (check my Github profile for the code) so I may have some experience on this.

**Comment by Matuiss2** [comment]
Ah ok. One guy said it wasn't working so I changed it to relative path, I'll keep this open in case other people get the same mistake. I checked your works good job.
